/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UxResearchSurveyIndexImport } from './routes/ux-research-survey/index'
import { Route as UxResearchCommunityIndexImport } from './routes/ux-research-community/index'

// Create/Update Routes

const UxResearchSurveyIndexRoute = UxResearchSurveyIndexImport.update({
  id: '/ux-research-survey/',
  path: '/ux-research-survey/',
  getParentRoute: () => rootRoute,
} as any)

const UxResearchCommunityIndexRoute = UxResearchCommunityIndexImport.update({
  id: '/ux-research-community/',
  path: '/ux-research-community/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ux-research-community/': {
      id: '/ux-research-community/'
      path: '/ux-research-community'
      fullPath: '/ux-research-community'
      preLoaderRoute: typeof UxResearchCommunityIndexImport
      parentRoute: typeof rootRoute
    }
    '/ux-research-survey/': {
      id: '/ux-research-survey/'
      path: '/ux-research-survey'
      fullPath: '/ux-research-survey'
      preLoaderRoute: typeof UxResearchSurveyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/ux-research-community': typeof UxResearchCommunityIndexRoute
  '/ux-research-survey': typeof UxResearchSurveyIndexRoute
}

export interface FileRoutesByTo {
  '/ux-research-community': typeof UxResearchCommunityIndexRoute
  '/ux-research-survey': typeof UxResearchSurveyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/ux-research-community/': typeof UxResearchCommunityIndexRoute
  '/ux-research-survey/': typeof UxResearchSurveyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ux-research-community' | '/ux-research-survey'
  fileRoutesByTo: FileRoutesByTo
  to: '/ux-research-community' | '/ux-research-survey'
  id: '__root__' | '/ux-research-community/' | '/ux-research-survey/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UxResearchCommunityIndexRoute: typeof UxResearchCommunityIndexRoute
  UxResearchSurveyIndexRoute: typeof UxResearchSurveyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  UxResearchCommunityIndexRoute: UxResearchCommunityIndexRoute,
  UxResearchSurveyIndexRoute: UxResearchSurveyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ux-research-community/",
        "/ux-research-survey/"
      ]
    },
    "/ux-research-community/": {
      "filePath": "ux-research-community/index.tsx"
    },
    "/ux-research-survey/": {
      "filePath": "ux-research-survey/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
